### ISSUE TITLE
pip install regrid issue

### ISSUE THREAD

**Issue by matt-long** [NCAR/esmlab#117] opened 2019-04-11 19:20 UTC
Building environments using a conda environment file with the following pip directive

```
git+https://github.com/NCAR/esmlab.git
```
leads to the following error
```
Pip subprocess error:
  Could not find a version that satisfies the requirement esmlab-regrid (from esmlab==2019.3.16+140.gd3ce9a5->-r /gpfs/u/home/mclong/codes/NCAR-pangeo-tutorial/environments/condaenv.grstg34t.requirements.txt (line 4)) (from versions: )
No matching distribution found for esmlab-regrid (from esmlab==2019.3.16+140.gd3ce9a5->-r /gpfs/u/home/mclong/codes/NCAR-pangeo-tutorial/environments/condaenv.grstg34t.requirements.txt (line 4))
```
cc @andersy005

**Comment by matt-long** [comment] 2019-04-11 19:23
Adding 
```
git+https://github.com/NCAR/esmlab-regrid.git
```
seems to solve the problem.

**Comment by andersy005** [comment] 2019-04-11 19:32
@matt-long, thank you for reporting this. I ran into this issue before, and I meant to fix this issue a few days ago but I ended up forgetting. 

It is caused by the presence of esmlab-regrid in https://github.com/NCAR/esmlab/blob/master/requirements.txt#L4 and because esmlab-regrid is not on PyPI yet, pip gives up and throws the error. 

For the time being, the solution you propose should suffice until we have esmlab-regrid on PyPI.

**Comment by andersy005** [comment] 2019-05-06 22:04
Should be fixed now that `esmlab-regrid` is on PyPI: https://pypi.org/project/esmlab-regrid/

**Closed by andersy005** 2019-05-06 22:04 UTC
